language: node_js
dist: trusty
sudo: required
node_js:
- 6
env:
- PATH=$HOME/purescript:$PATH
git:
  depth: 1
notifications:
  email: false
cache:
  directories:
  - node_modules
  - packages/corge/node_modules
  - packages/grault/node_modules
  - packages/quux/node_modules
  - packages/quuz/node_modules
  - packages/qux/node_modules
  - packages/sdk/node_modules
  - packages/analytics/node_modules
  - packages/helpers/node_modules
  - packages/mjs/node_modules
  - packages/sdk/node_modules
  - packages/ui-components/node_modules
before_install: ./.travis/before_install.sh
install:
- TAG=$(wget -q -O - https://github.com/purescript/purescript/releases/latest --server-response
  --max-redirect 0 2>&1 | sed -n -e 's/.*Location:.*tag\///p')
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install -g bs-platform
- npm install
script:
- npm run test:once
after_success: ./.travis/after_success.sh

