language: node_js
dist: trusty
sudo: required
node_js:
- 6
env:
- PATH=$HOME/purescript:$PATH
git:
  depth: 1
notifications:
  email: false
cache:
  directories:
  - node_modules
  - packages/sdk/node_modules
  - packages/analytics/node_modules
  - packages/helpers/node_modules
  - packages/mjs/node_modules
  - packages/ui-components/node_modules
before_install: ./.travis/before_install.sh
install:
- npm install
script:
- npm t
after_success: ./.travis/after_success.sh
